/*
 * db-synth: A MIDI-controlled mono-voice digital synthesizer built on top of the
 *           AVR DB microcontroller series.
 *
 * SPDX-FileCopyrightText: 2022 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 * SPDX-License-Identifier: BSD-3-Clause
 */

// this file was generated by generate.py. do not edit!

#pragma once

#include <avr/pgmspace.h>
#include <stdint.h>

#include "phase.h"

#define adsr_amplitude 0xff
#define adsr_samples_per_cycle 0x0200

static const uint8_t attack_curve[] PROGMEM = {
    0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x04, 0x05,
    0x06, 0x07, 0x08, 0x09, 0x09, 0x0a, 0x0b, 0x0c,
    0x0d, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x11, 0x12,
    0x13, 0x14, 0x15, 0x15, 0x16, 0x17, 0x18, 0x19,
    0x19, 0x1a, 0x1b, 0x1c, 0x1c, 0x1d, 0x1e, 0x1f,
    0x1f, 0x20, 0x21, 0x22, 0x23, 0x23, 0x24, 0x25,
    0x26, 0x26, 0x27, 0x28, 0x29, 0x29, 0x2a, 0x2b,
    0x2c, 0x2c, 0x2d, 0x2e, 0x2e, 0x2f, 0x30, 0x31,
    0x31, 0x32, 0x33, 0x34, 0x34, 0x35, 0x36, 0x36,
    0x37, 0x38, 0x39, 0x39, 0x3a, 0x3b, 0x3b, 0x3c,
    0x3d, 0x3d, 0x3e, 0x3f, 0x40, 0x40, 0x41, 0x42,
    0x42, 0x43, 0x44, 0x44, 0x45, 0x46, 0x46, 0x47,
    0x48, 0x48, 0x49, 0x4a, 0x4a, 0x4b, 0x4c, 0x4c,
    0x4d, 0x4e, 0x4e, 0x4f, 0x50, 0x50, 0x51, 0x52,
    0x52, 0x53, 0x54, 0x54, 0x55, 0x56, 0x56, 0x57,
    0x58, 0x58, 0x59, 0x59, 0x5a, 0x5b, 0x5b, 0x5c,
    0x5d, 0x5d, 0x5e, 0x5e, 0x5f, 0x60, 0x60, 0x61,
    0x62, 0x62, 0x63, 0x63, 0x64, 0x65, 0x65, 0x66,
    0x66, 0x67, 0x68, 0x68, 0x69, 0x69, 0x6a, 0x6b,
    0x6b, 0x6c, 0x6c, 0x6d, 0x6e, 0x6e, 0x6f, 0x6f,
    0x70, 0x71, 0x71, 0x72, 0x72, 0x73, 0x73, 0x74,
    0x75, 0x75, 0x76, 0x76, 0x77, 0x78, 0x78, 0x79,
    0x79, 0x7a, 0x7a, 0x7b, 0x7b, 0x7c, 0x7d, 0x7d,
    0x7e, 0x7e, 0x7f, 0x7f, 0x80, 0x80, 0x81, 0x82,
    0x82, 0x83, 0x83, 0x84, 0x84, 0x85, 0x85, 0x86,
    0x86, 0x87, 0x87, 0x88, 0x89, 0x89, 0x8a, 0x8a,
    0x8b, 0x8b, 0x8c, 0x8c, 0x8d, 0x8d, 0x8e, 0x8e,
    0x8f, 0x8f, 0x90, 0x90, 0x91, 0x91, 0x92, 0x92,
    0x93, 0x93, 0x94, 0x94, 0x95, 0x95, 0x96, 0x96,
    0x97, 0x97, 0x98, 0x98, 0x99, 0x99, 0x9a, 0x9a,
    0x9b, 0x9b, 0x9c, 0x9c, 0x9d, 0x9d, 0x9e, 0x9e,
    0x9f, 0x9f, 0xa0, 0xa0, 0xa1, 0xa1, 0xa2, 0xa2,
    0xa3, 0xa3, 0xa4, 0xa4, 0xa4, 0xa5, 0xa5, 0xa6,
    0xa6, 0xa7, 0xa7, 0xa8, 0xa8, 0xa9, 0xa9, 0xaa,
    0xaa, 0xaa, 0xab, 0xab, 0xac, 0xac, 0xad, 0xad,
    0xae, 0xae, 0xaf, 0xaf, 0xaf, 0xb0, 0xb0, 0xb1,
    0xb1, 0xb2, 0xb2, 0xb2, 0xb3, 0xb3, 0xb4, 0xb4,
    0xb5, 0xb5, 0xb6, 0xb6, 0xb6, 0xb7, 0xb7, 0xb8,
    0xb8, 0xb9, 0xb9, 0xb9, 0xba, 0xba, 0xbb, 0xbb,
    0xbb, 0xbc, 0xbc, 0xbd, 0xbd, 0xbe, 0xbe, 0xbe,
    0xbf, 0xbf, 0xc0, 0xc0, 0xc0, 0xc1, 0xc1, 0xc2,
    0xc2, 0xc2, 0xc3, 0xc3, 0xc4, 0xc4, 0xc4, 0xc5,
    0xc5, 0xc6, 0xc6, 0xc6, 0xc7, 0xc7, 0xc8, 0xc8,
    0xc8, 0xc9, 0xc9, 0xca, 0xca, 0xca, 0xcb, 0xcb,
    0xcb, 0xcc, 0xcc, 0xcd, 0xcd, 0xcd, 0xce, 0xce,
    0xce, 0xcf, 0xcf, 0xd0, 0xd0, 0xd0, 0xd1, 0xd1,
    0xd1, 0xd2, 0xd2, 0xd3, 0xd3, 0xd3, 0xd4, 0xd4,
    0xd4, 0xd5, 0xd5, 0xd5, 0xd6, 0xd6, 0xd6, 0xd7,
    0xd7, 0xd8, 0xd8, 0xd8, 0xd9, 0xd9, 0xd9, 0xda,
    0xda, 0xda, 0xdb, 0xdb, 0xdb, 0xdc, 0xdc, 0xdc,
    0xdd, 0xdd, 0xdd, 0xde, 0xde, 0xde, 0xdf, 0xdf,
    0xe0, 0xe0, 0xe0, 0xe1, 0xe1, 0xe1, 0xe2, 0xe2,
    0xe2, 0xe3, 0xe3, 0xe3, 0xe3, 0xe4, 0xe4, 0xe4,
    0xe5, 0xe5, 0xe5, 0xe6, 0xe6, 0xe6, 0xe7, 0xe7,
    0xe7, 0xe8, 0xe8, 0xe8, 0xe9, 0xe9, 0xe9, 0xea,
    0xea, 0xea, 0xeb, 0xeb, 0xeb, 0xeb, 0xec, 0xec,
    0xec, 0xed, 0xed, 0xed, 0xee, 0xee, 0xee, 0xef,
    0xef, 0xef, 0xef, 0xf0, 0xf0, 0xf0, 0xf1, 0xf1,
    0xf1, 0xf2, 0xf2, 0xf2, 0xf2, 0xf3, 0xf3, 0xf3,
    0xf4, 0xf4, 0xf4, 0xf4, 0xf5, 0xf5, 0xf5, 0xf6,
    0xf6, 0xf6, 0xf6, 0xf7, 0xf7, 0xf7, 0xf8, 0xf8,
    0xf8, 0xf8, 0xf9, 0xf9, 0xf9, 0xfa, 0xfa, 0xfa,
    0xfa, 0xfb, 0xfb, 0xfb, 0xfc, 0xfc, 0xfc, 0xfc,
    0xfd, 0xfd, 0xfd, 0xfd, 0xfe, 0xfe, 0xfe, 0xff,
};

static const uint8_t decay_release_curve[] PROGMEM = {
    0x00, 0x01, 0x03, 0x04, 0x06, 0x07, 0x09, 0x0a,
    0x0c, 0x0d, 0x0f, 0x10, 0x12, 0x13, 0x15, 0x16,
    0x18, 0x19, 0x1a, 0x1c, 0x1d, 0x1f, 0x20, 0x21,
    0x23, 0x24, 0x25, 0x27, 0x28, 0x2a, 0x2b, 0x2c,
    0x2d, 0x2f, 0x30, 0x31, 0x33, 0x34, 0x35, 0x36,
    0x38, 0x39, 0x3a, 0x3b, 0x3d, 0x3e, 0x3f, 0x40,
    0x41, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x4a,
    0x4b, 0x4c, 0x4d, 0x4e, 0x4f, 0x50, 0x51, 0x52,
    0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b,
    0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62, 0x63,
    0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b,
    0x6c, 0x6d, 0x6e, 0x6f, 0x6f, 0x70, 0x71, 0x72,
    0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x78, 0x79,
    0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7e, 0x7f, 0x80,
    0x81, 0x82, 0x82, 0x83, 0x84, 0x85, 0x86, 0x86,
    0x87, 0x88, 0x89, 0x8a, 0x8a, 0x8b, 0x8c, 0x8d,
    0x8d, 0x8e, 0x8f, 0x8f, 0x90, 0x91, 0x92, 0x92,
    0x93, 0x94, 0x94, 0x95, 0x96, 0x97, 0x97, 0x98,
    0x99, 0x99, 0x9a, 0x9b, 0x9b, 0x9c, 0x9d, 0x9d,
    0x9e, 0x9f, 0x9f, 0xa0, 0xa0, 0xa1, 0xa2, 0xa2,
    0xa3, 0xa4, 0xa4, 0xa5, 0xa5, 0xa6, 0xa7, 0xa7,
    0xa8, 0xa8, 0xa9, 0xaa, 0xaa, 0xab, 0xab, 0xac,
    0xac, 0xad, 0xad, 0xae, 0xaf, 0xaf, 0xb0, 0xb0,
    0xb1, 0xb1, 0xb2, 0xb2, 0xb3, 0xb3, 0xb4, 0xb4,
    0xb5, 0xb5, 0xb6, 0xb6, 0xb7, 0xb7, 0xb8, 0xb8,
    0xb9, 0xb9, 0xba, 0xba, 0xbb, 0xbb, 0xbc, 0xbc,
    0xbd, 0xbd, 0xbe, 0xbe, 0xbf, 0xbf, 0xbf, 0xc0,
    0xc0, 0xc1, 0xc1, 0xc2, 0xc2, 0xc3, 0xc3, 0xc3,
    0xc4, 0xc4, 0xc5, 0xc5, 0xc5, 0xc6, 0xc6, 0xc7,
    0xc7, 0xc8, 0xc8, 0xc8, 0xc9, 0xc9, 0xca, 0xca,
    0xca, 0xcb, 0xcb, 0xcb, 0xcc, 0xcc, 0xcd, 0xcd,
    0xcd, 0xce, 0xce, 0xce, 0xcf, 0xcf, 0xcf, 0xd0,
    0xd0, 0xd1, 0xd1, 0xd1, 0xd2, 0xd2, 0xd2, 0xd3,
    0xd3, 0xd3, 0xd4, 0xd4, 0xd4, 0xd5, 0xd5, 0xd5,
    0xd6, 0xd6, 0xd6, 0xd6, 0xd7, 0xd7, 0xd7, 0xd8,
    0xd8, 0xd8, 0xd9, 0xd9, 0xd9, 0xda, 0xda, 0xda,
    0xda, 0xdb, 0xdb, 0xdb, 0xdc, 0xdc, 0xdc, 0xdc,
    0xdd, 0xdd, 0xdd, 0xdd, 0xde, 0xde, 0xde, 0xdf,
    0xdf, 0xdf, 0xdf, 0xe0, 0xe0, 0xe0, 0xe0, 0xe1,
    0xe1, 0xe1, 0xe1, 0xe2, 0xe2, 0xe2, 0xe2, 0xe3,
    0xe3, 0xe3, 0xe3, 0xe4, 0xe4, 0xe4, 0xe4, 0xe5,
    0xe5, 0xe5, 0xe5, 0xe5, 0xe6, 0xe6, 0xe6, 0xe6,
    0xe7, 0xe7, 0xe7, 0xe7, 0xe7, 0xe8, 0xe8, 0xe8,
    0xe8, 0xe8, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xea,
    0xea, 0xea, 0xea, 0xea, 0xeb, 0xeb, 0xeb, 0xeb,
    0xeb, 0xec, 0xec, 0xec, 0xec, 0xec, 0xed, 0xed,
    0xed, 0xed, 0xed, 0xed, 0xee, 0xee, 0xee, 0xee,
    0xee, 0xef, 0xef, 0xef, 0xef, 0xef, 0xef, 0xf0,
    0xf0, 0xf0, 0xf0, 0xf0, 0xf0, 0xf1, 0xf1, 0xf1,
    0xf1, 0xf1, 0xf1, 0xf1, 0xf2, 0xf2, 0xf2, 0xf2,
    0xf2, 0xf2, 0xf3, 0xf3, 0xf3, 0xf3, 0xf3, 0xf3,
    0xf3, 0xf4, 0xf4, 0xf4, 0xf4, 0xf4, 0xf4, 0xf4,
    0xf5, 0xf5, 0xf5, 0xf5, 0xf5, 0xf5, 0xf5, 0xf5,
    0xf6, 0xf6, 0xf6, 0xf6, 0xf6, 0xf6, 0xf6, 0xf6,
    0xf7, 0xf7, 0xf7, 0xf7, 0xf7, 0xf7, 0xf7, 0xf7,
    0xf8, 0xf8, 0xf8, 0xf8, 0xf8, 0xf8, 0xf8, 0xf8,
    0xf9, 0xf9, 0xf9, 0xf9, 0xf9, 0xf9, 0xf9, 0xf9,
    0xf9, 0xfa, 0xfa, 0xfa, 0xfa, 0xfa, 0xfa, 0xfa,
    0xfa, 0xfa, 0xfa, 0xfb, 0xfb, 0xfb, 0xfb, 0xfb,
    0xfb, 0xfb, 0xfb, 0xfb, 0xfb, 0xfc, 0xfc, 0xfc,
    0xfc, 0xfc, 0xfc, 0xfc, 0xfc, 0xfc, 0xfc, 0xfc,
    0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd,
    0xfd, 0xfd, 0xfd, 0xfe, 0xfe, 0xfe, 0xfe, 0xfe,
    0xfe, 0xfe, 0xfe, 0xfe, 0xfe, 0xfe, 0xfe, 0xff,
};

static const struct {
    const char *description;
    phase_t step;
} times[] = {
    {
        .description = "2 ms",
        .step        = {0x00055555},
    },
    {
        .description = "3 ms",
        .step        = {0x00038e39},
    },
    {
        .description = "4 ms",
        .step        = {0x0002aaab},
    },
    {
        .description = "5 ms",
        .step        = {0x00022222},
    },
    {
        .description = "6 ms",
        .step        = {0x0001c71c},
    },
    {
        .description = "8 ms",
        .step        = {0x00015555},
    },
    {
        .description = "9 ms",
        .step        = {0x00012f68},
    },
    {
        .description = "10 ms",
        .step        = {0x00011111},
    },
    {
        .description = "12 ms",
        .step        = {0x0000e38e},
    },
    {
        .description = "13 ms",
        .step        = {0x0000d20d},
    },
    {
        .description = "15 ms",
        .step        = {0x0000b60b},
    },
    {
        .description = "16 ms",
        .step        = {0x0000aaab},
    },
    {
        .description = "18 ms",
        .step        = {0x000097b4},
    },
    {
        .description = "19 ms",
        .step        = {0x00008fb8},
    },
    {
        .description = "21 ms",
        .step        = {0x00008208},
    },
    {
        .description = "23 ms",
        .step        = {0x000076ba},
    },
    {
        .description = "24 ms",
        .step        = {0x000071c7},
    },
    {
        .description = "26 ms",
        .step        = {0x00006907},
    },
    {
        .description = "28 ms",
        .step        = {0x00006186},
    },
    {
        .description = "30 ms",
        .step        = {0x00005b06},
    },
    {
        .description = "31 ms",
        .step        = {0x00005816},
    },
    {
        .description = "33 ms",
        .step        = {0x000052bf},
    },
    {
        .description = "35 ms",
        .step        = {0x00004e05},
    },
    {
        .description = "37 ms",
        .step        = {0x000049cd},
    },
    {
        .description = "39 ms",
        .step        = {0x00004604},
    },
    {
        .description = "41 ms",
        .step        = {0x0000429a},
    },
    {
        .description = "43 ms",
        .step        = {0x00003f81},
    },
    {
        .description = "46 ms",
        .step        = {0x00003b5d},
    },
    {
        .description = "48 ms",
        .step        = {0x000038e4},
    },
    {
        .description = "50 ms",
        .step        = {0x0000369d},
    },
    {
        .description = "52 ms",
        .step        = {0x00003483},
    },
    {
        .description = "55 ms",
        .step        = {0x000031a6},
    },
    {
        .description = "57 ms",
        .step        = {0x00002fe8},
    },
    {
        .description = "60 ms",
        .step        = {0x00002d83},
    },
    {
        .description = "62 ms",
        .step        = {0x00002c0b},
    },
    {
        .description = "65 ms",
        .step        = {0x00002a03},
    },
    {
        .description = "68 ms",
        .step        = {0x00002828},
    },
    {
        .description = "70 ms",
        .step        = {0x00002702},
    },
    {
        .description = "73 ms",
        .step        = {0x00002568},
    },
    {
        .description = "76 ms",
        .step        = {0x000023ee},
    },
    {
        .description = "79 ms",
        .step        = {0x00002291},
    },
    {
        .description = "82 ms",
        .step        = {0x0000214d},
    },
    {
        .description = "85 ms",
        .step        = {0x00002020},
    },
    {
        .description = "88 ms",
        .step        = {0x00001f08},
    },
    {
        .description = "92 ms",
        .step        = {0x00001dae},
    },
    {
        .description = "95 ms",
        .step        = {0x00001cbe},
    },
    {
        .description = "98 ms",
        .step        = {0x00001bdd},
    },
    {
        .description = "102 ms",
        .step        = {0x00001ac5},
    },
    {
        .description = "106 ms",
        .step        = {0x000019c3},
    },
    {
        .description = "109 ms",
        .step        = {0x0000190d},
    },
    {
        .description = "113 ms",
        .step        = {0x0000182a},
    },
    {
        .description = "117 ms",
        .step        = {0x00001757},
    },
    {
        .description = "121 ms",
        .step        = {0x00001691},
    },
    {
        .description = "125 ms",
        .step        = {0x000015d8},
    },
    {
        .description = "129 ms",
        .step        = {0x0000152b},
    },
    {
        .description = "133 ms",
        .step        = {0x00001488},
    },
    {
        .description = "137 ms",
        .step        = {0x000013ef},
    },
    {
        .description = "142 ms",
        .step        = {0x0000133b},
    },
    {
        .description = "146 ms",
        .step        = {0x000012b4},
    },
    {
        .description = "151 ms",
        .step        = {0x00001215},
    },
    {
        .description = "156 ms",
        .step        = {0x00001181},
    },
    {
        .description = "161 ms",
        .step        = {0x000010f6},
    },
    {
        .description = "166 ms",
        .step        = {0x00001073},
    },
    {
        .description = "171 ms",
        .step        = {0x00000ff8},
    },
    {
        .description = "176 ms",
        .step        = {0x00000f84},
    },
    {
        .description = "181 ms",
        .step        = {0x00000f16},
    },
    {
        .description = "187 ms",
        .step        = {0x00000e9a},
    },
    {
        .description = "192 ms",
        .step        = {0x00000e39},
    },
    {
        .description = "198 ms",
        .step        = {0x00000dcb},
    },
    {
        .description = "204 ms",
        .step        = {0x00000d63},
    },
    {
        .description = "210 ms",
        .step        = {0x00000d01},
    },
    {
        .description = "216 ms",
        .step        = {0x00000ca4},
    },
    {
        .description = "222 ms",
        .step        = {0x00000c4d},
    },
    {
        .description = "229 ms",
        .step        = {0x00000bed},
    },
    {
        .description = "235 ms",
        .step        = {0x00000b9f},
    },
    {
        .description = "242 ms",
        .step        = {0x00000b49},
    },
    {
        .description = "249 ms",
        .step        = {0x00000af7},
    },
    {
        .description = "256 ms",
        .step        = {0x00000aab},
    },
    {
        .description = "263 ms",
        .step        = {0x00000a62},
    },
    {
        .description = "271 ms",
        .step        = {0x00000a14},
    },
    {
        .description = "278 ms",
        .step        = {0x000009d3},
    },
    {
        .description = "286 ms",
        .step        = {0x0000098c},
    },
    {
        .description = "294 ms",
        .step        = {0x0000094a},
    },
    {
        .description = "302 ms",
        .step        = {0x0000090b},
    },
    {
        .description = "310 ms",
        .step        = {0x000008cf},
    },
    {
        .description = "319 ms",
        .step        = {0x0000088f},
    },
    {
        .description = "328 ms",
        .step        = {0x00000853},
    },
    {
        .description = "337 ms",
        .step        = {0x0000081a},
    },
    {
        .description = "346 ms",
        .step        = {0x000007e4},
    },
    {
        .description = "355 ms",
        .step        = {0x000007b1},
    },
    {
        .description = "365 ms",
        .step        = {0x0000077b},
    },
    {
        .description = "375 ms",
        .step        = {0x00000748},
    },
    {
        .description = "385 ms",
        .step        = {0x00000718},
    },
    {
        .description = "395 ms",
        .step        = {0x000006ea},
    },
    {
        .description = "406 ms",
        .step        = {0x000006ba},
    },
    {
        .description = "416 ms",
        .step        = {0x00000690},
    },
    {
        .description = "427 ms",
        .step        = {0x00000665},
    },
    {
        .description = "439 ms",
        .step        = {0x00000638},
    },
    {
        .description = "450 ms",
        .step        = {0x00000611},
    },
    {
        .description = "462 ms",
        .step        = {0x000005e9},
    },
    {
        .description = "474 ms",
        .step        = {0x000005c3},
    },
    {
        .description = "487 ms",
        .step        = {0x0000059b},
    },
    {
        .description = "500 ms",
        .step        = {0x00000576},
    },
    {
        .description = "513 ms",
        .step        = {0x00000553},
    },
    {
        .description = "526 ms",
        .step        = {0x00000531},
    },
    {
        .description = "540 ms",
        .step        = {0x0000050f},
    },
    {
        .description = "554 ms",
        .step        = {0x000004ee},
    },
    {
        .description = "568 ms",
        .step        = {0x000004cf},
    },
    {
        .description = "583 ms",
        .step        = {0x000004af},
    },
    {
        .description = "598 ms",
        .step        = {0x00000491},
    },
    {
        .description = "613 ms",
        .step        = {0x00000474},
    },
    {
        .description = "629 ms",
        .step        = {0x00000457},
    },
    {
        .description = "645 ms",
        .step        = {0x0000043c},
    },
    {
        .description = "661 ms",
        .step        = {0x00000422},
    },
    {
        .description = "678 ms",
        .step        = {0x00000407},
    },
    {
        .description = "696 ms",
        .step        = {0x000003ec},
    },
    {
        .description = "713 ms",
        .step        = {0x000003d4},
    },
    {
        .description = "731 ms",
        .step        = {0x000003bc},
    },
    {
        .description = "750 ms",
        .step        = {0x000003a4},
    },
    {
        .description = "769 ms",
        .step        = {0x0000038d},
    },
    {
        .description = "788 ms",
        .step        = {0x00000377},
    },
    {
        .description = "808 ms",
        .step        = {0x00000361},
    },
    {
        .description = "829 ms",
        .step        = {0x0000034b},
    },
    {
        .description = "850 ms",
        .step        = {0x00000336},
    },
    {
        .description = "871 ms",
        .step        = {0x00000323},
    },
    {
        .description = "893 ms",
        .step        = {0x0000030f},
    },
    {
        .description = "915 ms",
        .step        = {0x000002fc},
    },
    {
        .description = "938 ms",
        .step        = {0x000002e9},
    },
    {
        .description = "962 ms",
        .step        = {0x000002d7},
    },
    {
        .description = "986 ms",
        .step        = {0x000002c5},
    },
    {
        .description = "1.01 s",
        .step        = {0x000002b4},
    },
    {
        .description = "1.04 s",
        .step        = {0x000002a3},
    },
    {
        .description = "1.06 s",
        .step        = {0x00000293},
    },
    {
        .description = "1.09 s",
        .step        = {0x00000283},
    },
    {
        .description = "1.11 s",
        .step        = {0x00000273},
    },
    {
        .description = "1.14 s",
        .step        = {0x00000264},
    },
    {
        .description = "1.17 s",
        .step        = {0x00000255},
    },
    {
        .description = "1.20 s",
        .step        = {0x00000247},
    },
    {
        .description = "1.23 s",
        .step        = {0x00000238},
    },
    {
        .description = "1.26 s",
        .step        = {0x0000022b},
    },
    {
        .description = "1.29 s",
        .step        = {0x0000021d},
    },
    {
        .description = "1.32 s",
        .step        = {0x00000210},
    },
    {
        .description = "1.36 s",
        .step        = {0x00000204},
    },
    {
        .description = "1.39 s",
        .step        = {0x000001f7},
    },
    {
        .description = "1.42 s",
        .step        = {0x000001eb},
    },
    {
        .description = "1.46 s",
        .step        = {0x000001df},
    },
    {
        .description = "1.49 s",
        .step        = {0x000001d4},
    },
    {
        .description = "1.53 s",
        .step        = {0x000001c9},
    },
    {
        .description = "1.57 s",
        .step        = {0x000001be},
    },
    {
        .description = "1.61 s",
        .step        = {0x000001b3},
    },
    {
        .description = "1.65 s",
        .step        = {0x000001a8},
    },
    {
        .description = "1.69 s",
        .step        = {0x0000019e},
    },
    {
        .description = "1.73 s",
        .step        = {0x00000195},
    },
    {
        .description = "1.77 s",
        .step        = {0x0000018b},
    },
    {
        .description = "1.81 s",
        .step        = {0x00000181},
    },
    {
        .description = "1.86 s",
        .step        = {0x00000178},
    },
    {
        .description = "1.90 s",
        .step        = {0x0000016f},
    },
    {
        .description = "1.95 s",
        .step        = {0x00000166},
    },
    {
        .description = "2.00 s",
        .step        = {0x0000015e},
    },
    {
        .description = "2.05 s",
        .step        = {0x00000156},
    },
    {
        .description = "2.10 s",
        .step        = {0x0000014e},
    },
    {
        .description = "2.15 s",
        .step        = {0x00000146},
    },
    {
        .description = "2.20 s",
        .step        = {0x0000013e},
    },
    {
        .description = "2.25 s",
        .step        = {0x00000136},
    },
    {
        .description = "2.31 s",
        .step        = {0x0000012f},
    },
    {
        .description = "2.36 s",
        .step        = {0x00000128},
    },
    {
        .description = "2.42 s",
        .step        = {0x00000121},
    },
    {
        .description = "2.48 s",
        .step        = {0x0000011a},
    },
    {
        .description = "2.54 s",
        .step        = {0x00000113},
    },
    {
        .description = "2.60 s",
        .step        = {0x0000010d},
    },
    {
        .description = "2.67 s",
        .step        = {0x00000106},
    },
    {
        .description = "2.73 s",
        .step        = {0x00000100},
    },
    {
        .description = "2.80 s",
        .step        = {0x000000fa},
    },
    {
        .description = "2.86 s",
        .step        = {0x000000f4},
    },
    {
        .description = "2.93 s",
        .step        = {0x000000ee},
    },
    {
        .description = "3.00 s",
        .step        = {0x000000e9},
    },
    {
        .description = "3.08 s",
        .step        = {0x000000e3},
    },
    {
        .description = "3.15 s",
        .step        = {0x000000de},
    },
    {
        .description = "3.23 s",
        .step        = {0x000000d9},
    },
    {
        .description = "3.31 s",
        .step        = {0x000000d4},
    },
    {
        .description = "3.38 s",
        .step        = {0x000000cf},
    },
    {
        .description = "3.47 s",
        .step        = {0x000000ca},
    },
    {
        .description = "3.55 s",
        .step        = {0x000000c5},
    },
    {
        .description = "3.64 s",
        .step        = {0x000000c0},
    },
    {
        .description = "3.72 s",
        .step        = {0x000000bc},
    },
    {
        .description = "3.81 s",
        .step        = {0x000000b7},
    },
    {
        .description = "3.90 s",
        .step        = {0x000000b3},
    },
    {
        .description = "4.00 s",
        .step        = {0x000000af},
    },
    {
        .description = "4.10 s",
        .step        = {0x000000ab},
    },
    {
        .description = "4.19 s",
        .step        = {0x000000a7},
    },
    {
        .description = "4.29 s",
        .step        = {0x000000a3},
    },
    {
        .description = "4.40 s",
        .step        = {0x0000009f},
    },
    {
        .description = "4.50 s",
        .step        = {0x0000009b},
    },
    {
        .description = "4.61 s",
        .step        = {0x00000098},
    },
    {
        .description = "4.72 s",
        .step        = {0x00000094},
    },
    {
        .description = "4.84 s",
        .step        = {0x00000090},
    },
    {
        .description = "4.95 s",
        .step        = {0x0000008d},
    },
    {
        .description = "5.07 s",
        .step        = {0x0000008a},
    },
    {
        .description = "5.20 s",
        .step        = {0x00000087},
    },
    {
        .description = "5.32 s",
        .step        = {0x00000083},
    },
    {
        .description = "5.45 s",
        .step        = {0x00000080},
    },
    {
        .description = "5.58 s",
        .step        = {0x0000007d},
    },
    {
        .description = "5.71 s",
        .step        = {0x0000007a},
    },
    {
        .description = "5.85 s",
        .step        = {0x00000077},
    },
    {
        .description = "5.99 s",
        .step        = {0x00000075},
    },
    {
        .description = "6.13 s",
        .step        = {0x00000072},
    },
    {
        .description = "6.28 s",
        .step        = {0x0000006f},
    },
    {
        .description = "6.43 s",
        .step        = {0x0000006d},
    },
    {
        .description = "6.59 s",
        .step        = {0x0000006a},
    },
    {
        .description = "6.74 s",
        .step        = {0x00000068},
    },
    {
        .description = "6.91 s",
        .step        = {0x00000065},
    },
    {
        .description = "7.07 s",
        .step        = {0x00000063},
    },
    {
        .description = "7.24 s",
        .step        = {0x00000061},
    },
    {
        .description = "7.41 s",
        .step        = {0x0000005e},
    },
    {
        .description = "7.59 s",
        .step        = {0x0000005c},
    },
    {
        .description = "7.77 s",
        .step        = {0x0000005a},
    },
    {
        .description = "7.96 s",
        .step        = {0x00000058},
    },
    {
        .description = "8.15 s",
        .step        = {0x00000056},
    },
    {
        .description = "8.35 s",
        .step        = {0x00000054},
    },
    {
        .description = "8.55 s",
        .step        = {0x00000052},
    },
    {
        .description = "8.75 s",
        .step        = {0x00000050},
    },
    {
        .description = "8.96 s",
        .step        = {0x0000004e},
    },
    {
        .description = "9.17 s",
        .step        = {0x0000004c},
    },
    {
        .description = "9.39 s",
        .step        = {0x0000004a},
    },
    {
        .description = "9.62 s",
        .step        = {0x00000049},
    },
    {
        .description = "9.85 s",
        .step        = {0x00000047},
    },
    {
        .description = "10.08 s",
        .step        = {0x00000045},
    },
    {
        .description = "10.33 s",
        .step        = {0x00000044},
    },
    {
        .description = "10.57 s",
        .step        = {0x00000042},
    },
    {
        .description = "10.83 s",
        .step        = {0x00000041},
    },
    {
        .description = "11.08 s",
        .step        = {0x0000003f},
    },
    {
        .description = "11.35 s",
        .step        = {0x0000003e},
    },
    {
        .description = "11.62 s",
        .step        = {0x0000003c},
    },
    {
        .description = "11.90 s",
        .step        = {0x0000003b},
    },
    {
        .description = "12.18 s",
        .step        = {0x00000039},
    },
    {
        .description = "12.47 s",
        .step        = {0x00000038},
    },
    {
        .description = "12.77 s",
        .step        = {0x00000037},
    },
    {
        .description = "13.08 s",
        .step        = {0x00000035},
    },
    {
        .description = "13.39 s",
        .step        = {0x00000034},
    },
    {
        .description = "13.71 s",
        .step        = {0x00000033},
    },
    {
        .description = "14.04 s",
        .step        = {0x00000032},
    },
    {
        .description = "14.37 s",
        .step        = {0x00000031},
    },
    {
        .description = "14.72 s",
        .step        = {0x00000030},
    },
    {
        .description = "15.07 s",
        .step        = {0x0000002e},
    },
    {
        .description = "15.43 s",
        .step        = {0x0000002d},
    },
    {
        .description = "15.80 s",
        .step        = {0x0000002c},
    },
    {
        .description = "16.17 s",
        .step        = {0x0000002b},
    },
    {
        .description = "16.56 s",
        .step        = {0x0000002a},
    },
    {
        .description = "16.95 s",
        .step        = {0x00000029},
    },
    {
        .description = "17.36 s",
        .step        = {0x00000028},
    },
    {
        .description = "17.77 s",
        .step        = {0x00000027},
    },
    {
        .description = "18.20 s",
        .step        = {0x00000026},
    },
    {
        .description = "18.63 s",
        .step        = {0x00000026},
    },
    {
        .description = "19.08 s",
        .step        = {0x00000025},
    },
    {
        .description = "19.53 s",
        .step        = {0x00000024},
    },
    {
        .description = "20.00 s",
        .step        = {0x00000023},
    },
};
