// Code generated by "synth-datagen v0.0.1-0.20260215194038-53f001d0579d"; DO NOT EDIT.

// SPDX-FileCopyrightText: 2022-present Rafael G. Martins <rafael@rafaelmartins.eng.br>
// SPDX-License-Identifier: BSD-3-Clause

#pragma once

#include <avr/io.h>

#define cpu_frqsel CLKCTRL_FRQSEL_24M_gc
#define opamp_timebase 23
#define output_offset 0x01ff
#define timer_tcb_ccmp 500
#define timer_tcb_clksel TCB_CLKSEL_DIV1_gc
