/*
 * db-synth: A MIDI-controlled mono-voice digital synthesizer built on top of the
 *           AVR DB microcontroller series.
 *
 * SPDX-FileCopyrightText: 2022 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 * SPDX-License-Identifier: BSD-3-Clause
 */

// this file was generated by generate.py. do not edit!

#pragma once

#include <avr/io.h>

#define cpu_frqsel CLKCTRL_FRQSEL_24M_gc
#define opamp_timebase 23
#define timer_tcb_ccmp 500
#define timer_tcb_clksel TCB_CLKSEL_DIV1_gc
#define oscillator_waveform_amplitude 0x01ff
