// Code generated by "synth-datagen v0.0.1-0.20260215194038-53f001d0579d"; DO NOT EDIT.

// SPDX-FileCopyrightText: 2022-present Rafael G. Martins <rafael@rafaelmartins.eng.br>
// SPDX-License-Identifier: BSD-3-Clause

#pragma once

#include <avr/io.h>

#define midi_usart_baud 3072
#define midi_usart_rxmode USART_RXMODE_NORMAL_gc
#define midi_usart_cmode USART_CMODE_ASYNCHRONOUS_gc
