/*
 * db-synth: A MIDI-controlled mono-voice digital synthesizer built on top of the
 *           AVR DB microcontroller series.
 *
 * SPDX-FileCopyrightText: 2022 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 * SPDX-License-Identifier: BSD-3-Clause
 */

// this file was generated by generate.py. do not edit!

#pragma once

#include <avr/io.h>

#define midi_usart_baud 3072
#define midi_usart_rxmode USART_RXMODE_NORMAL_gc
#define midi_usart_cmode USART_CMODE_ASYNCHRONOUS_gc
