// Code generated by "synth-datagen v0.0.1-0.20260215194038-53f001d0579d"; DO NOT EDIT.

// SPDX-FileCopyrightText: 2022-present Rafael G. Martins <rafael@rafaelmartins.eng.br>
// SPDX-License-Identifier: BSD-3-Clause

#pragma once

#define oled_twi_mbaud 20
