name: Build website and deploy to GitHub Pages

on:
  push:
    paths:
      - '.github/workflows/pages.yml'
      - 'README.md'
      - 'build-aux/**'
      - 'pcb/**'
      - 'website/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-ibom:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check out InteractiveHtmlBom
        uses: actions/checkout@v3
        with:
          repository: openscopeproject/InteractiveHtmlBom
          ref: v2.5.0
          path: InteractiveHtmlBom

      - name: Generate interactive BOM
        run: ./build-aux/ibom.sh index.html

      - name: Upload interactive BOM
        uses: actions/upload-artifact@v3
        with:
          name: ibom
          path: index.html

  # build-midi:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Generate MIDI Implementation Chart
  #       run: ./build-aux/midi.sh midi.pdf

  #     - name: Upload MIDI Implementation Chart
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: midi
  #         path: midi.pdf

  build-website:
    runs-on: ubuntu-latest
    needs:
      - build-ibom
      # - build-midi
    steps:
      - name: Install blogc
        run: |
          echo "deb [trusted=yes] https://deb.rgm.io/blogc-snapshot $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/blogc.list
          sudo apt update
          sudo apt install -y blogc-make

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Build
        run: |
          export OUTPUT_DIR=$(pwd)/prefix
          pushd website > /dev/null
          blogc-make
          popd > /dev/null

      - name: Download interactive BOM
        uses: actions/download-artifact@v3
        with:
          name: ibom
          path: prefix/ibom

      # - name: Download MIDI Implementation Chart
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: midi
      #     path: prefix

      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: prefix

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-website
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
